export const FETCH_NFT_REQUEST = 'FETCH_NFT_REQUEST';
export const FETCH_NFT_SUCCESS = 'FETCH_NFT_SUCCESS';
export const FETCH_NFT_FAILURE = 'FETCH_NFT_FAILURE';

export const FETCH_POAP_REQUEST = 'FETCH_POAP_REQUEST';
export const FETCH_POAP_SUCCESS = 'FETCH_POAP_SUCCESS';
export const FETCH_POAP_FAILURE = 'FETCH_POAP_FAILURE';
